### ISSUE TITLE
Add .gitignore, update README

### ISSUE THREAD

**Issue by Shumyk** [AndrreyCastillo/AimPractice#15]
1. Create .gitignore and add there IDEA generated files, class files
2. Update README.md with info on how to run the application in IDEA and fix typos.

**Comment by Shumyk** [comment]
@AndrreyCastillo I don't have the rights to add Labels, can you do it, please?

**Comment by su7edja** [comment]
@Shumyk @AndrreyCastillo I'm interested in working on this. Can you assign this to me?

**Comment by su7edja** [comment]
I created a PR for this: https://github.com/AndrreyCastillo/AimPractice/pull/17
