### ISSUE TITLE
Change title of program from "Hand-Eye Coordination" to "AimPractice" or "Aim Practice" ?

### ISSUE THREAD

**Issue by AndrreyCastillo** [AndrreyCastillo/AimPractice#5]
Not sure about this one yet

**Comment by sandydebug** [comment]
I can solve this problem

**Comment by AndrreyCastillo** [comment]
@sandydebug Sure, just know that Hacktoberfest doesn't start until October 1st and I'm not %100 if that will count towards your goal for a free shirt.
I'll let you pick the right name :)

**Comment by Shumyk** [comment]
#14 
Created pull request. Managed to run the application in Intellij, found plenty of points of improvement.
